import React from 'react';

export default function TermsOfService() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '60px 20px', fontFamily: 'system-ui, -apple-system, sans-serif', color: '#0f172a', lineHeight: '1.7' }}>
      <header style={{ marginBottom: '40px', borderBottom: '1px solid #e2e8f0', paddingBottom: '20px' }}>
        <a href="/" style={{ textDecoration: 'none', color: '#6366f1', fontWeight: 600, fontSize: '0.95rem' }}>← Back to Home</a>
        <h1 style={{ marginTop: '20px', fontSize: '2.25rem', fontWeight: 800, color: '#0f172a' }}>Terms of Service</h1>
        <p style={{ color: '#64748b', margin: '8px 0 0 0' }}>Last updated: October 2026</p>
      </header>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0f172a', marginBottom: '16px' }}>1. Agreement to Terms</h2>
        <p>
          By accessing or using our website and scanner tools, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not access or use the platform.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0f172a', marginBottom: '16px' }}>2. Subscription Plan and Billing</h2>
        <p>
          We offer a Pro subscription tier priced at €14.99/month for early access founding members. Subscriptions are billed on a recurring monthly basis and can be canceled at any time via the Stripe Billing Portal in your Settings tab.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0f172a', marginBottom: '16px' }}>3. Fair Use & Abuse Prevention</h2>
        <p>
          To prevent resource abuse, we rate limit anonymous queries to 3 free scans per day. Logged in and Pro users must utilize their quotas in a fair manner. Automated scraping or reverse engineering of our scan API is strictly prohibited.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0f172a', marginBottom: '16px' }}>4. Disclaimer of Warranties</h2>
        <p>
          The scan results, citation rates, and visibility scores are generated by third-party Large Language Models (LLMs) and search APIs. We make no guarantees regarding the accuracy, persistence, or stability of LLM citation scores, as AI engines frequently update their algorithms.
        </p>
      </section>
    </div>
  );
}
